config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      root to: "base#index"
      resources :users do
          resources :permissions

          put "permissions", to: "permissions#set",
                            as: "set_permissions"
      end
  end

    root "projects#index"
    resources :projects do
        resources :tickets
    end
    resources :users
    resources :files
    get '/signin', to: "sessions#new"
    post '/signin', to: "sessions#create"
    delete '/signout', to: "sessions#destroy", as: "signout"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>
        <%if content_for?(:title) %>
            <%= yield(:title)%>
        <% else %>
            Ticketee
        <% end %>
    </title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <!-- javascript_include_tag "application" -->
  <%= csrf_meta_tags %>
</head>
<body>

    <% flash.each do |key, value| %>
        <div class='flash' id='<%= key %>'>
            <%= value %>
        </div>
    <% end %>
<%= yield %>
    <nav>
        <% if current_user %>
            Signed in as <%= current_user.email %>
            <%= link_to "Sign out", signout_path, method: :delete %>
            <% admins_only do %>
                <%= link_to "Admin", admin_root_path %>
            <% end %>
        <% else %>
            <ul>
                <li><%= link_to "Sign up", new_user_path %></li>
                <li><%= link_to "Sign in", signin_path %></li>
            </ul>
        <% end %>
    </nav>
</body>
</html>